import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {activeInput,buildStoryBrief} from '../shared/story-brief.mjs';import {validateInput,PRODUCT} from '../server/product.mjs';
const base={child_name:'Eliška',child_age:4,appearance_description:'Hnědé vlasy a brýle',theme:'Kouzelný les',companion_mode:'catalog',companion_id:'lisi-fox',personal_wish:'Ráda pomáhá zvířatům.'};
test('self-contained manual prompt: complete output, explicit manual mode, no secrets or placeholders',()=>{const {prompt,customer}=buildStoryBrief(base);for(const text of ['Eliška','Kouzelný les','Lisa','Hnědé vlasy','25–40','1536×1024','15 bodů','21 bodů','A4','PDF','6 stran','6 samostatných','konzisten','#C62828'])assert.ok(prompt.toLowerCase().includes(text.toLowerCase()),text);for(const text of ['{{','lisi-fox','2026-10-v2','/assets/','approval_token','API_KEY'])assert.ok(!prompt.includes(text),text);assert.ok(prompt.startsWith('EXECUTION_MODE=manual_preview'));assert.ok(prompt.includes('Nepředstírá schválení serverem'));assert.equal(customer.child_age,4);assert.equal(customer.companion.vzhled.includes('satchel'),true);});
test('only active choice is sent, own drafts are untouched',()=>{const draft={...base,custom_theme:'Tajná zahrada',custom_companion:'Harry Potter'};const {customer,prompt}=buildStoryBrief(draft);assert.ok(!prompt.includes('Tajná zahrada'));assert.ok(!prompt.includes('Harry Potter'));assert.equal(draft.custom_companion,'Harry Potter');assert.equal(activeInput(draft).custom_companion,'');const own=buildStoryBrief({...draft,theme:'Vlastní téma',companion_mode:'custom'});assert.equal(own.customer.theme,'Tajná zahrada');assert.equal(own.customer.companion.popis,'Harry Potter');assert.ok(!own.prompt.includes('lisi-fox'));});
test('no companion and photo instructions without any image payload/path',()=>{const {prompt,customer}=buildStoryBrief({...base,companion_mode:'none',appearance_description:''},{photoPresent:true});assert.equal(customer.companion.volba,'Bez parťáka');assert.ok(prompt.includes('fotografii dítěte přiloženou zvlášť'));assert.ok(!prompt.includes('data:image'));assert.ok(!prompt.includes('blob:'));assert.ok(!prompt.includes('C:\\'));});
test('explicit selections and age are required; known name is valid',()=>{for(const raw of [{...base,child_age:null},{...base,theme:''},{...base,companion_mode:''},{...base,companion_mode:'custom',custom_companion:''}])assert.throws(()=>buildStoryBrief(raw),/INVALID_INPUT/);assert.equal(validateInput(activeInput({...base,companion_mode:'custom',custom_companion:'Harry Potter'})).valid,true);});
test('manual and API use the same core rules and exactly the same active customer data',()=>{const manual=buildStoryBrief(base),api=buildStoryBrief(base,{target:'api'});assert.deepEqual(api.customer,manual.customer);for(const rule of ['DRAMATURGIE A PRAVIDLA PROSTŘEDÍ','ROZMANITOST ŠESTI SCÉN','KONZISTENCE POSTAV A PŘEDMĚTŮ','ILUSTRACE A OBTÍŽNOST','KONTROLA SKUTEČNÝCH OBRÁZKŮ A PDF']){assert.ok(api.instructions.includes(rule));assert.ok(manual.instructions.includes(rule));}assert.ok(api.instructions.startsWith('EXECUTION_MODE=production'));assert.ok(manual.instructions.startsWith('EXECUTION_MODE=manual_preview'));});
test('standalone route, no preselection, custom cards first, homepage keeps product gallery',async()=>{const html=await readFile(new URL('../dist/vytvorit/index.html',import.meta.url),'utf8'),home=await readFile(new URL('../dist/index.html',import.meta.url),'utf8'),map=await readFile(new URL('../dist/sitemap.xml',import.meta.url),'utf8');assert.ok(html.includes('noindex,follow'));assert.ok(!map.includes('/vytvorit/'));assert.ok(!html.includes(' checked'));assert.ok(!html.includes(' selected'));assert.ok(html.indexOf('value="custom"')<html.indexOf('value="catalog:'));assert.ok(html.indexOf('value="Vlastní téma"')<html.indexOf('value="Kouzelný les"'));assert.ok(html.includes(PRODUCT.priceCzk+' Kč'));assert.ok(!home.includes('id="creator"'));assert.ok(!home.includes('id="theme-grid"'));assert.ok(!home.includes('id="partaci"'));assert.ok(home.includes('href="/vytvorit/"'));assert.equal((home.match(/data-page="/g)||[]).length,6);assert.ok(html.includes('name="companion"'));assert.ok(html.includes('name="theme"'));});
