import test from 'node:test';import assert from 'node:assert/strict';import {createHmac} from 'node:crypto';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';
import {openStore} from '../server/local-store.mjs';import {createOrderEngine} from '../server/order-engine.mjs';import {preflight} from '../server/preflight.mjs';import {verifyStripeSignature} from '../server/payment-webhook.mjs';import {createWorker} from '../server/worker.mjs';
const input={child_name:'Eliška',child_age:4,theme:'Kouzelný les',appearance_description:'Hnědé vlasy',companion_mode:'catalog',companion_id:'lisi-fox'};
function services(extra={}){const approvals=new Map(),audit=[];return {provider:'fixture',orderBudget:40,checkProvider:async()=>({available:true,supportsExactSettings:true,estimatedTotalCost:20}),moderate:async()=>({status:'approved'}),assessRights:async()=>({status:'cleared'}),recordCheck:async x=>audit.push(x),saveApproval:async a=>approvals.set(a.token,a),loadApproval:async t=>approvals.get(t),audit,...extra};}
async function setup(t){const dir=mkdtempSync(path.join(tmpdir(),'pohadka-'));const store=openStore(path.join(dir,'test.sqlite'));t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true});});const svc=services();const approved=await preflight(input,svc);let now=Date.now();const engine=createOrderEngine({store,provider:'fixture',preflightServices:svc,clock:()=>now});const order=await engine.create({approvalToken:approved.approval_token,input});const payment={id:'event-1',paymentId:'pay-1',orderId:order.id,type:'paid',amount:8000,currency:'czk'};return {store,engine,order,payment,svc,advance:ms=>now+=ms};}
const receipt=(stage,verifiedImages=[])=>({costCzk:1,requestId:stage,outputKey:stage,verifiedPages:6,
 visualReview:{outputKey:stage,passed:true,matchesText:true,consistentIdentity:true,consistentEquipment:true,worldRules:true,coloringStyle:true},
 illustrationsReview:{passed:true,distinctScenes:true,consistentIdentityAndEquipment:true,outputKeys:verifiedImages.map(image=>image.outputKey)},
 pdfReview:{outputKey:stage,passed:true,sixPages:true,singleTitle:true,visibleContent:true,correctColorPhrases:true,embeddedCzechFont:true,noUnintendedCropping:true}});
const adapters=(extra={})=>({textModel:'fixture',estimate:()=>1,execute:async({stage,verifiedImages})=>receipt(stage,verifiedImages),...extra});
test('original, custom and known companions; rights uncertainty is not a technical ban',async()=>{for(const extra of [{},{companion_mode:'none'},{companion_mode:'custom',companion_type:'Vlastní zadání',custom_companion:'Můj měsíční skřítek'},{companion_mode:'custom',companion_type:'Vlastní zadání',custom_companion:'Harry Potter'}])assert.equal((await preflight({...input,...extra},services())).outcome,'clear');const r=await preflight(input,services({assessRights:async()=>({status:'unknown'})}));assert.equal(r.outcome,'clear');assert.equal(r.checks.rights,'unresolved');assert.ok(r.message_cs.includes('nepotvrzuje oprávnění'));assert.equal(r.checks.technical,'supported');assert.equal((await preflight(input,services({assessRights:undefined}))).outcome,'clear');assert.equal((await preflight(input,services({assessRights:async()=>({status:'restricted'})}))).outcome,'clarify');assert.equal((await preflight(input,services({moderate:async()=>({status:'clarify'})}))).outcome,'clarify');assert.equal((await preflight(input,services({moderate:async()=>({status:'blocked'})}))).outcome,'unsupported');});
test('audit excludes customer text',async()=>{const svc=services();await preflight(input,svc);const audit=JSON.stringify(svc.audit);assert.ok(!audit.includes('Eliška'));assert.ok(!audit.includes('Hnědé'));assert.ok(audit.includes('rulesVersion'));});
test('verified payment is idempotent, wrong amounts rejected, six images exactly once',async t=>{const {engine,order,payment,store}=await setup(t);assert.throws(()=>engine.acceptPayment({...payment,amount:1}),/MISMATCH/);engine.acceptPayment(payment);assert.equal(engine.acceptPayment(payment).duplicate,true);assert.equal(engine.acceptPayment({...payment,id:'event-2'}).duplicate,true);assert.deepEqual(engine.pending(),[order.id]);let calls=0;assert.equal((await engine.run(order.id,adapters({execute:async({stage,verifiedImages})=>{calls++;return receipt(stage,verifiedImages);}}))).status,'ready');assert.equal(calls,8);assert.equal((await engine.run(order.id,adapters())).claimed,false);assert.equal((await engine.status(order.id,order.accessToken)).canDownload,true);await assert.rejects(engine.file(order.id,'foreign-token',{}),/ACCESS_DENIED/);assert.equal(store.transaction(s=>Object.values(s.metrics).filter(e=>e.name==='purchase').length),1);});
test('provider refusal stops attempts and exposes refund path',async t=>{const {engine,order,payment}=await setup(t);engine.acceptPayment(payment);let calls=0;await engine.run(order.id,adapters({execute:async()=>{calls++;throw Object.assign(Error('refused'),{code:'PROVIDER_REFUSED'});}}));assert.equal(calls,1);assert.equal((await engine.status(order.id,order.accessToken)).status,'needs_action');assert.equal((await engine.run(order.id,adapters())).claimed,false);assert.equal((await engine.requestRefund(order.id,order.accessToken)).status,'refund_pending');engine.confirmRefund(order.id,'verified-refund');assert.equal((await engine.status(order.id,order.accessToken)).status,'refunded');});
test('actual over-budget cost persists and download remains disabled',async t=>{const {engine,order,payment,store}=await setup(t);engine.acceptPayment(payment);await engine.run(order.id,adapters({execute:async()=>({costCzk:41,requestId:'actual',outputKey:'paid-output'})}));assert.equal(store.transaction(s=>s.orders[order.id].costCzk),41);assert.equal((await engine.status(order.id,order.accessToken)).canDownload,false);});
test('lease timeout is not retried; expiration revokes access and removes files',async t=>{const {engine,order,payment,advance,store}=await setup(t);engine.acceptPayment(payment);let calls=0;await engine.run(order.id,adapters({execute:async()=>{calls++;advance(300001);return {costCzk:1,requestId:'late',outputKey:'late-file'};}}));assert.equal(calls,1);assert.equal(store.transaction(s=>s.orders[order.id].costCzk),1);assert.equal((await engine.run(order.id,adapters())).claimed,false);advance(31*86400000);const removed=[];await engine.expire({deletePrivate:async key=>removed.push(key)});assert.deepEqual(removed,['late-file']);await assert.rejects(engine.status(order.id,order.accessToken),/ACCESS_DENIED/);});
test('SQLite survives restart and backup',()=>{const dir=mkdtempSync(path.join(tmpdir(),'pohadka-store-')),file=path.join(dir,'db.sqlite');let store=openStore(file);try{store.transaction(s=>s.audit.push({reason:'TEST'}));store.backup(path.join(dir,'backup.sqlite'));store.close();store=openStore(file);assert.equal(store.transaction(s=>s.audit.length),1);const restored=openStore(path.join(dir,'backup.sqlite'));assert.equal(restored.transaction(s=>s.audit.length),1);restored.close();}finally{store.close();rmSync(dir,{recursive:true,force:true});}});
test('webhook raw-body signature and timestamp',async()=>{const now=Math.floor(Date.now()/1000),raw=JSON.stringify({id:'evt'}),secret='test-only';const sig=createHmac('sha256',secret).update(now+'.'+raw).digest('hex');assert.equal((await verifyStripeSignature(raw,`t=${now},v1=${sig}`,secret,now)).id,'evt');await assert.rejects(verifyStripeSignature(raw+' ',`t=${now},v1=${sig}`,secret,now),/SIGNATURE/);await assert.rejects(verifyStripeSignature(raw,`t=${now},v1=${sig}`,secret,now+301),/EXPIRED/);});
test('HTML routes, canonical redirects, real 404 and private server exclusion',async()=>{const asset=text=>({base64:Buffer.from(text).toString('base64'),type:'text/html'});const worker=createWorker({'/index.html':asset('<h1>Home</h1>'),'/ukazky/index.html':asset('six pages'),'/404.html':asset('missing'),'/server/private':asset('secret')});const get=p=>worker.fetch(new Request('https://example.com'+p));assert.equal((await get('/ukazky/')).status,200);assert.equal((await get('/ukazky')).status,308);assert.equal((await get('/index.html')).headers.get('location'),'https://example.com/');assert.equal((await get('/missing')).status,404);assert.equal((await get('/server/private')).status,404);assert.equal((await get('/api/readiness')).headers.get('x-robots-tag'),'noindex');});

test('invalid PDF receipt is recorded but never released',async t=>{const {engine,order,payment,store}=await setup(t);engine.acceptPayment(payment);await engine.run(order.id,adapters({execute:async({stage,verifiedImages})=>({...receipt(stage,verifiedImages),verifiedPages:1})}));assert.equal((await engine.status(order.id,order.accessToken)).canDownload,false);assert.equal(store.transaction(s=>s.orders[order.id].costCzk),8);assert.equal(store.transaction(s=>s.orders[order.id].reason),'INVALID_PDF');});


test('unreviewed image stops production, cannot become reference and is not retried',async t=>{
 const {engine,order,payment,store}=await setup(t);engine.acceptPayment(payment);const calls=[];
 await engine.run(order.id,adapters({execute:async({stage,verifiedImages})=>{calls.push(stage);assert.equal(verifiedImages.length,0);const result=receipt(stage,verifiedImages);if(stage==='image:1')delete result.visualReview;return result;}}));
 assert.deepEqual(calls,['story','image:1']);assert.equal((await engine.status(order.id,order.accessToken)).canDownload,false);assert.equal(store.transaction(s=>s.orders[order.id].reason),'IMAGE_REVIEW_REQUIRED');assert.equal((await engine.run(order.id,adapters())).claimed,false);
});
test('batch diversity and rendered PDF verification are mandatory for delivery',async t=>{
 for(const missing of ['illustrationsReview','pdfReview']){const {engine,order,payment,store}=await setup(t);engine.acceptPayment(payment);
  await engine.run(order.id,adapters({execute:async({stage,verifiedImages})=>{if(stage.startsWith('image:'))assert.equal(verifiedImages.length,Number(stage.split(':')[1])-1);const result=receipt(stage,verifiedImages);if(stage==='pdf')delete result[missing];return result;}}));
  assert.equal((await engine.status(order.id,order.accessToken)).canDownload,false);assert.equal(store.transaction(s=>s.orders[order.id].reason),missing==='illustrationsReview'?'ILLUSTRATIONS_REVIEW_REQUIRED':'PDF_REVIEW_REQUIRED');
 }
});
