import {PRODUCT,escapeHtml as e} from '../server/product.mjs';
export const OPERATOR=Object.freeze({name:'Petr Slavík',ico:'05695961',address:'Nová 114, 768 21 Kvasice',email:'petrlavikweb@gmail.com',vatPayer:false});
const mail=`<a href="mailto:${OPERATOR.email}">${OPERATOR.email}</a>`;
export const operatorDetails=()=>`<dl class="legal-details"><dt>Provozovatel</dt><dd>${e(OPERATOR.name)}</dd><dt>IČO</dt><dd>${OPERATOR.ico}</dd><dt>Sídlo</dt><dd>${e(OPERATOR.address)}</dd><dt>Evidence</dt><dd>Podnikající fyzická osoba zapsaná v živnostenském rejstříku.</dd><dt>DPH</dt><dd>Provozovatel není plátce DPH.</dd><dt>Kontakt</dt><dd>${mail}</dd></dl>`;
const paragraph=text=>`<p>${text}</p>`;
const section=(title,text)=>`<section><h2>${title}</h2>${paragraph(text)}</section>`;
export const LEGAL_PAGES=[
 {path:'/smluvni-podminky/',title:'Smluvní podmínky',description:'Pravidla používání webu Pohádkové omalovánky a informace o personalizovaném PDF.',lead:'Přehledně o zadání, výsledku a vašich právech.',body:
 section('1. Kdo web provozuje','Web Pohádkové omalovánky provozuje níže uvedený podnikatel. Podmínky se vztahují na používání webu a přípravu zadání personalizovaného příběhu.')+operatorDetails()+
 section('2. Co si můžete připravit',`Produktem je česká pohádka vytvořená pomocí AI na ${PRODUCT.pages} stranách v jednom PDF. Každá stránka obsahuje krátký text a jednu omalovánku, přizpůsobené zadanému věku. Uváděná konečná cena je ${PRODUCT.priceCzk} Kč za jeden sešit, bez předplatného. Provozovatel není plátce DPH. Prohlížení ukázky a příprava či kopírování zadání jsou bez platby. Samotné vyplnění formuláře nevytváří placenou objednávku.`)+
 section('3. Zadání','Formulář je určen dospělému rodiči nebo jiné oprávněné pečující osobě. Uvádějte jen potřebné informace; nepřidávejte citlivé údaje o dítěti. Vlastní či známou postavu lze zadat; tím ale nevzniká záruka jejího přijetí ani oprávnění výsledek komerčně využívat.')+
 section('4. Kontrola, objednávka a platba','Kontrola může vyžadovat úpravu zadání. Předběžný výsledek není zárukou následného generování. Placenou objednávku lze uzavřít jen prostřednictvím dostupného platebního procesu s uvedenou cenou, způsobem dodání a termínem. Dokud není platební proces dostupný, formulář platbu nevybírá a placenou výrobu neobjednává. Kopírování promptu nevolá placené AI API.')+
 section('5. Výsledek a použití','AI může udělat chybu. Před použitím zkontrolujte příběh a obrázky; nesprávný nebo nedodaný sjednaný výsledek lze reklamovat. PDF je určeno k otevření v běžné PDF čtečce a tisku na A4 na šířku. Oprávnění k dalšímu využití konkrétního obsahu se posuzuje podle příslušných práv; úspěšné generování samo nepotvrzuje komerční licenci. Tím nejsou omezena zákonná práva spotřebitele.')+
 section('6. Odstoupení od smlouvy','U smlouvy uzavřené na dálku má spotřebitel zpravidla 14 dní na odstoupení. U digitálního obsahu dodávaného bez hmotného nosiče lze o toto právo přijít při zahájení plnění jen při splnění zákonných podmínek, včetně předchozího výslovného souhlasu s dodáním před uplynutím lhůty, poučení o ztrátě práva a příslušného potvrzení. Pouhé vyplnění formuláře, odsouhlasení těchto podmínek ani zavření cookie lišty takový souhlas nenahrazuje. Pro odstoupení kontaktujte provozovatele s identifikací objednávky.')+
 section('7. Reklamace a řešení problému',`Problém popište na ${mail}; u objednávky připojte její identifikaci a požadovaný způsob řešení. Reklamaci digitálního obsahu vyřídíme v přiměřené době podle zákona. Pokud nelze dodat sjednaný výsledek, řešením může být dohodnutá úprava zadání nebo vrácení platby; změnu postavy neprovedeme bez vašeho výběru. Vyřízení AI nesmí omezit zákonné právo na odstranění vady, slevu nebo odstoupení, jsou-li pro ně splněny podmínky.`)+
 section('8. Mimosoudní řešení a závěr','Spotřebitelský spor lze řešit prostřednictvím České obchodní inspekce, Štěpánská 567/15, 120 00 Praha 2; informace a návrh jsou na <a href="https://coi.gov.cz/informace-o-adr/">stránce ČOI o mimosoudním řešení sporů</a>. Uplatní se české právo, aniž by byla dotčena povinná ochrana spotřebitele. Pro uzavřenou objednávku je rozhodující znění potvrzené při jejím uzavření. Tyto podmínky jsou účinné od 9. října 2026.')},
 {path:'/soukromi/',title:'Ochrana osobních údajů',description:'Jak zacházíme se zadáním, kontaktními zprávami a cookies.',lead:'Jen údaje potřebné pro vaše zadání. Bez reklamního sledování.',body:
 section('Kdo odpovídá za vaše údaje','Správcem osobních údajů pro tento web je:')+operatorDetails()+
 section('Zadání dítěte','Jméno, věk, popis vzhledu, svět, parťák, přání zůstávají v paměti otevřené stránky. Web je neukládá do URL, cookies, localStorage ani návštěvnické analytiky. Obnovením nebo zavřením stránky se tato pracovní data ztratí. Neposílejte zdravotní ani jiné citlivé údaje.')+
 section('Kdy se údaje mohou odeslat','Při kontrole web nejdříve ověřuje dostupnost serverové služby bez odeslání formuláře. Je-li dostupná, po kliknutí na Zkontrolovat zadání odešle údaje serverové funkci Supabase pro technické ověření formuláře. Funkce zadání trvale neukládá a nepředává generativní AI. Do databáze ukládá pouze technický výsledek kontroly, čas a verzi pravidel, bez jména nebo přání dítěte. Kopírování promptu pouze předá text do vaší schránky. Pokud text vložíte do jiné služby, platí podmínky a zásady této vámi zvolené služby. Připojení zákaznického generátoru vyžaduje aktualizaci těchto informací o skutečném příjemci dat a dobách uchování.')+
 section('Kontakt a účel zpracování',`Pokud napíšete na ${mail}, zpracujeme vaši adresu a obsah zprávy pro vyřízení dotazu, předsmluvní jednání nebo plnění smlouvy. Navazující ochrana nároků a bezpečnost se opírá o oprávněný zájem; případné povinné účetní údaje o zákonnou povinnost. Pouhý dotaz uchováváme po dobu potřebnou k jeho vyřízení a navazující komunikaci. Bez této komunikace vám nemůžeme odpovědět. Zákaznické příběhy nezveřejňujeme jako reklamní ukázky.`)+
 section('Hosting, e-mail a písma','Web může být dostupný přes OpenAI Sites, GitHub Pages nebo místní vývojový server. Serverovou kontrolu a databázi zajišťuje Supabase; databázový projekt je umístěný ve Frankfurtu. Tyto služby mohou zpracovávat technické údaje jako IP adresu, čas požadavku a informace o prohlížeči pro doručení a zabezpečení webu. Kontaktní e-mail používá službu Gmail společnosti Google. Písma načítáme přes Google Fonts, při čemž prohlížeč odesílá poskytovateli síťový požadavek včetně IP adresy. Tyto externí služby mohou zpracovávat údaje i mimo EHP podle svého režimu ochrany údajů. Nastavení cookies neřídí technické záznamy hostingu ani načítání písem. AI poskytovatel a platební brána dosud nejsou připojeny.')+
 section('Cookies a uchování','Web neprovozuje reklamní ani analytické cookies. Jediná preference, kterou naše lišta zapisuje, je technický záznam o jejím zavření na nejvýše 180 dní; neobsahuje zadání dítěte. Podrobnosti jsou na <a href="/cookies/">stránce Cookies</a>. Hosting může používat vlastní nezbytné mechanismy pro přihlášení a bezpečný přístup. Samotná stránka neukládá výsledná PDF do serverového úložiště, a proto zde neslibujeme dosud nezavedené lhůty jejich serverového mazání.')+
 section('Vaše práva',`Podle podmínek GDPR můžete požádat o přístup, opravu, výmaz, omezení či přenositelnost a vznést námitku proti zpracování založenému na oprávněném zájmu. Je-li základem souhlas, lze jej odvolat. Žádost pošlete na ${mail}; může být nutné přiměřeně ověřit totožnost. Obvykle odpovíme do jednoho měsíce, případné zákonné prodloužení vysvětlíme. Stížnost můžete podat u <a href="https://uoou.gov.cz/">Úřadu pro ochranu osobních údajů</a>. Web neprovádí rozhodování s právními či obdobně významnými účinky založené výhradně na automatizovaném zpracování.`)+
 paragraph('Aktualizováno 9. října 2026. Tento popis odpovídá aktuálně připojeným funkcím webu.')},
 {path:'/cookies/',title:'Cookies',description:'Přehled nezbytného ukládání a nastavení cookies na webu.',lead:'Žádné reklamní sledování. Jen zapamatování vašeho nastavení.',body:
 section('Co web používá','Naše stránka nyní nezapíná analytické ani reklamní cookies nebo měřicí skripty. Není proto potřeba udělovat souhlas s nepoužívaným měřením. Lišta pouze vysvětluje současné nastavení; její zavření není souhlas s reklamou ani s obchodními podmínkami.')+
 section('Zapamatování lišty','Po kliknutí na „Rozumím“ nebo „Uložit nastavení“ uložíme technickou cookie <strong>fairytale_cookie_notice</strong>, která obsahuje pouze verzi oznámení. Platí pro tuto doménu a nejvýše 180 dní, používá SameSite=Lax a na HTTPS příznak Secure. Změna verze oznámení nebo smazání cookie lištu znovu zobrazí. Pokud prohlížeč ukládání zakazuje, web funguje dál; oznámení se při další návštěvě může objevit znovu.')+
 section('Další technické mechanismy','Soukromý hosting může vyžadovat vlastní technické cookies pro přihlášení a ochranu přístupu. Ty nejsou návštěvnickým měřením a tato lišta je nemaže. Písma Google Fonts se načítají externím síťovým požadavkem; nejde o službu zapínanou souhlasem s analytikou. Více informací najdete v <a href="/soukromi/">ochraně osobních údajů</a>.')+
 section('Jak nastavení změnit','Oznámení můžete kdykoli otevřít tlačítkem „Nastavení cookies“ v patičce. Cookies lze také odstranit v nastavení prohlížeče. Pokud přidáme volitelné měření, musí nejprve dostat vlastní popis a výslovnou volbu; samotné dnešní potvrzení je nepovolí.')+
 `<button type="button" class="button outline" data-cookie-open>Otevřít nastavení cookies</button>`}
];
export const cookieNotice=()=>`<aside class="cookie-notice" id="cookie-notice" aria-labelledby="cookie-title" hidden><div class="cookie-inner"><div class="cookie-copy"><h2 id="cookie-title">Malá poznámka ke cookies</h2><p>Používáme jen nezbytné ukládání nastavení. Reklamní ani analytické cookies nezapínáme. <a href="/cookies/">Více o cookies</a></p></div><div class="cookie-actions"><button type="button" class="button outline" id="cookie-settings" aria-expanded="false" aria-controls="cookie-details">Nastavení</button><button type="button" class="button" id="cookie-confirm">Rozumím</button></div><section id="cookie-details" class="cookie-details" hidden><h3>Vaše soukromí, přehledně</h3><dl><dt>Nezbytné</dt><dd>Zapamatování této lišty a technické fungování webu.</dd><dt>Statistika a reklama</dt><dd>Nepoužíváme. Žádné volitelné sledování se tímto potvrzením nezapne.</dd></dl><p>Nastavení lišty si pamatujeme nejvýše 180 dní. Zadání dítěte do cookies nevkládáme.</p><button type="button" class="button outline" id="cookie-save">Uložit nastavení</button><p id="cookie-storage-status" role="status"></p></section></div></aside><script src="/cookies.js" defer></script>`;
