export const SITE='https://moje-pohadka-kouzelne-omalovanky.lifecore.chatgpt.site';
export const CONTACT='petrlavikweb@gmail.com';
export const faqs=[
 ['Co bude součástí příběhu a kolik stojí?','Česká pohádka na míru se šesti navazujícími omalovánkami v jednom PDF stojí 80 Kč. Jednorázově, bez předplatného. Vzorový příběh si můžete stáhnout zdarma.'],
 ['Pro jak staré děti je pohádka určená?','Pro děti od 3 do 9 let. Délka textu i složitost obrázků se přizpůsobí věku. Vzor na této stránce ukazuje příběh pro čtyřleté dítě.'],
 ['Potřebuji fotografii dítěte?','Ne. Můžete zadat jméno, věk a krátký popis vzhledu. Volitelná fotografie slouží jako inspirace pro kreslenou postavu, nikoli jako předloha k přesnému obkreslení.'],
 ['Může mít dítě vlastního parťáka?','Ano. Vyberte některého z našich kamarádů, popište vlastního, nebo nechte dítě vyrazit na výpravu samotné.'],
 ['Jak si omalovánky vytisknu?','Stáhněte PDF a vytiskněte ho na běžný papír A4 na šířku, jednostranně. Zvolte přizpůsobení tisknutelné oblasti. Černobílý tisk stačí; barevný zachová i barevné nápovědy v textu. PDF můžete vytisknout také v copycentru.'],
 ['Jak vznikne vlastní příběh?','Vše probíhá přímo na webu. Vyberete hrdinu, svět a případně parťáka, zkontrolujete zadání a AI z něj vytvoří pohádku s omalovánkami. Výsledkem je PDF ke stažení a tisku.']
];
export const themes=['Kouzelný les','Zvířecí kamarádi','Zatoulaný obláček','Podmořský svět','Vesmír','Dinosauři'];
export const pages=[
 {path:'/pohadka-na-miru/',title:'Pohádka na míru se jménem dítěte a omalovánkami',description:'Jak se jméno, věk a zájmy dítěte promění v český příběh se šesti omalovánkami. Prohlédněte si celý vzor.',heading:'Příběh, ve kterém se dítě pozná.',lead:'Jméno není jen na obálce. Patří hrdinovi, který objevuje, pomáhá a hledá vlastní řešení.',sections:[['Co si vyberete','Jméno a věk dítěte, prostředí příběhu a případně parťáka. Můžete přidat zájmy nebo přání konkrétní scény. Fotografii nepotřebujete.'],['Jeden příběh od začátku do konce','Šest scén na sebe navazuje. Text je nad obrázkem a barevná fráze napoví, který předmět vybarvit. V ukázce Eliška s liškou pomáhají lesní květině.'],['Co se mění podle věku','Pro 3–4 roky připravujeme 25–40 slov na stranu, pro 5–6 let 35–50 a pro 7–9 let 45–65. Starší děti mohou dostat složitější scénu; veřejný vzor nyní ukazuje věk 4 roky.']],sample:true},
 {path:'/omalovanky-z-fotky/',title:'Omalovánky z fotky dítěte s vlastním příběhem',description:'Fotografie je volitelná. Přečtěte si, jak ji používáme pro kreslenou podobu a jak funguje příběh bez fotografie.',heading:'Fotka může pomoci. Není podmínkou.',lead:'Dítě se promění v kresleného hrdinu nového příběhu. Nejde o přesné obkreslení fotografie.',sections:[['Raději bez fotografie?','Napište barvu a délku vlasů, účes a případně brýle. Nepotřebujeme příjmení, datum narození ani adresu dítěte.'],['Když fotografii přidáte','Vyberte jednu čitelnou fotku v JPEG nebo PNG do 10 MB. Poslouží jako inspirace pro kreslenou podobu dítěte. V náhledu ji můžete kdykoli odstranit.'],['Co fotografie nezaručuje','Výsledkem je stylizovaná ilustrace. Podobnost a konzistence všech šesti scén se musí ověřit ve výrobě. Věk bereme z formuláře, nikoli z obličeje. Veřejná ukázka níže představuje fiktivní dítě, nikoli proměnu skutečné fotografie.']],sample:true},
 {path:'/omalovanky-pro-deti-3-4-roky/',title:'Jednoduché omalovánky pro děti 3–4 roky s příběhem',description:'Velké plochy, krátké české vyprávění a šest navazujících scén. Celá ukázka pro čtyřleté dítě k prohlédnutí i tisku.',heading:'Velké plochy pro malé pastelky.',lead:'Krátká pohádka k předčítání. Na každé straně jedna srozumitelná akce a prostor pro vlastní barvy.',sections:[['Prohlédněte si skutečný vzor','Eliška a kouzelný les je ukázka pro čtyřleté dítě. Můžete si projít všech šest stran a vyzkoušet tisk před rozhodnutím.'],['Čtěte a objevujte spolu','Nejprve přečtěte krátký text. Pak zkuste najít předmět, jehož barva je zvýrazněná. Dítě může použít také vlastní barvy; nejde o test ani povinný úkol.']],sample:true},
 {path:'/temata/zviratka/',title:'Pohádka o zvířátkách s omalovánkami na míru',description:'Lesní dobrodružství s dítětem a liškou. Prohlédněte si šestistránkový příběh a vyberte vlastní zvířecí téma.',heading:'Malé tlapky. Velké přátelství.',lead:'Zvířecí kamarád v příběhu pomáhá, objevuje a někdy sám potřebuje pomoc.',sections:[['Lesní příběh na ukázku','Eliška potká lišku u květiny. Společně hledají vodu, přejdou potůček a vrátí se zalít květinu. Na konci si odpočinou pod stromem.'],['Váš příběh může být jiný','Vyberte vlastní téma a parťáka: domácího mazlíčka, některou z našich postav nebo výpravu bez parťáka. Známou postavu automaticky nezamítáme podle jména.']],sample:true,theme:'Zvířecí kamarádi'},
 {path:'/navody/jak-vytisknout-omalovanky/',title:'Jak vytisknout omalovánky PDF na A4',description:'Jednoduchý návod: A4 na šířku, jednostranný tisk a správné měřítko. Vyzkoušejte bezplatné šestistránkové PDF.',heading:'Z PDF rovnou na stůl.',lead:'Stačí běžný papír A4 a pastelky. Nejprve zkuste jednu stranu.',sections:[['1. Stáhněte a otevřete PDF','Uložte soubor do zařízení. Otevřete jej v prohlížeči PDF a zvolte Tisk. Tiskněte PDF, nikoli screenshot náhledu webu.'],['2. Nastavte stránku','Papír A4, orientace na šířku, jedna stránka na list, jednostranný tisk. Zvolte Přizpůsobit tisknutelné oblasti, pokud tiskárna neumí tisknout až ke kraji.'],['3. Vyzkoušejte první list','Kresba je černobílá. Barevný tisk zachová i barevnou nápovědu v textu; černobílý tisk je použitelný také. Pokud část obrázku chybí, zkontrolujte orientaci a měřítko.'],['Nemáte tiskárnu?','Uložené PDF můžete vytisknout později nebo v copycentru. Soukromý zákaznický soubor nesdílejte veřejným odkazem.']],sample:true}
];
