export const CATALOG_VERSION = '2026-10-v3';
export const COMPANION_CATALOG = Object.freeze([
  {id:'pip-dog',name:'Pip',kind:'veselý pejsek',description:'Dodá odvahu a nikdy nenechá kamaráda samotného.',appearance:'Small puppy with long floppy ears, round muzzle, plain triangular neckerchief; no other clothes.',character:'Cheerful, supportive; helps the child carry and find things.'},
  {id:'lisi-fox',name:'Lisa',kind:'zvědavá liška',description:'Všimne si drobné stopy a ráda hledá nové cesty.',appearance:'Small fox with large triangular ears, broad white muzzle and tail tip, simple small cross-body satchel; no other clothes.',character:'Curious, observant; follows clues together with the child.'},
  {id:'borek-dragon',name:'Bořek',kind:'přátelský dráček',description:'Pomůže přes překážku a umí trpělivě naslouchat.',appearance:'Small friendly dragon with rounded wings, short rounded horns, plain vest, broad belly; no other clothes.',character:'Patient, gentle; helps safely reach objects without fire.'},
  {id:'blik-robot',name:'Blik',kind:'malý robot',description:'Rád zkouší nápady a učí se spolu s dítětem.',appearance:'Small rounded robot, two round eyes, square chest pocket, simple rounded limbs; no letters or screens with text.',character:'Thoughtful, playful; tests simple solutions, makes harmless mistakes.'},
  {id:'jiskra-unicorn',name:'Jiskra',kind:'kouzelný jednorožec',description:'Vnáší do výpravy fantazii a povzbuzuje ostatní.',appearance:'Small unicorn, one short rounded horn, simple flowing mane, one star medallion, no other clothes.',character:'Kind, imaginative; encourages the child and notices beauty.'},
  {id:'dino-dinosaur',name:'Bronťa',kind:'odvážný dinosaurus',description:'Odvaha pro něj znamená pomoci, i když má trochu strach.',appearance:'Small friendly dinosaur with rounded back plates and a plain small backpack, broad feet, gentle rounded muzzle.',character:'Brave and considerate; works with the child to overcome small obstacles.'},
  {id:'bublik-dolphin',name:'Bublík',kind:'hravý delfín',description:'Zná mořské cestičky a pomůže objevit poklady pod hladinou.',appearance:'Small friendly dolphin with rounded fins, gently curved body, large kind eyes and a plain small neckerchief; no other clothes.',character:'Playful, helpful; explores the sea together with the child.',artwork:'/assets/companions/bublik-dolphin.png'},
  {id:'pirko-bird',name:'Pírko',kind:'zvídavý ptáček',description:'Ukáže cestu mezi oblaky a všimne si všeho z výšky.',appearance:'Small rounded bird with a short beak, friendly eyes, small rounded wings and a plain tiny cross-body satchel; no other clothes.',character:'Curious, gentle; guides the child through the sky and helps find the way.',artwork:'/assets/companions/pirko-bird.png'},
  {id:'kori-turtle',name:'Kori',kind:'klidná mořská želvička',description:'Zná tiché mořské zátoky a pomůže najít bezpečnou cestu.',appearance:'Small sea turtle with a large simple oval shell divided into four broad rounded panels, four broad flippers, a rounded head and kind eyes. Sparse broad outlined oval spots on the head and flippers; no tiny textures, clothes or accessories. Preserve the four shell panels and four flippers.',character:'Calm, patient; guides the child through the sea and helps notice safe routes.',artwork:'/assets/companions/kori-turtle.webp'},
  {id:'oli-octopus',name:'Oli',kind:'šikovná chobotnička',description:'Má spoustu nápadů a osm šikovných chapadélek.',appearance:'Small cheerful octopus with a smooth rounded head, friendly eyes and exactly eight short thick rounded arms; two front arms gently curled. No tiny suckers, textures, clothes or accessories. Preserve all eight arms; viewpoint may hide some but never change their number.',character:'Inventive, helpful; holds and gently moves objects while the child decides what to do.',artwork:'/assets/companions/oli-octopus.webp'},
  {id:'vlnka-seahorse',name:'Vlnka',kind:'zvídavý mořský koník',description:'Objeví drobnou stopu i mezi vysokými mořskými řasami.',appearance:'Small friendly seahorse with a rounded S-shaped body, short rounded tubular snout, one small simple fan-shaped dorsal fin and one single coiled tail. Simple rounded scalloped crest along the head and back, four broad belly bands. Smooth outlines, no scales, tiny ribs, clothes or accessories.',character:'Curious, observant; finds clues among sea plants and explores with the child.',artwork:'/assets/companions/vlnka-seahorse.webp'},
  {id:'lumi-star',name:'Lumi',kind:'usměvavá hvězdička',description:'Posvítí na nový nápad a provází malého objevitele oblohou.',appearance:'Friendly living star with exactly five broad rounded body points, large kind eyes and a small central smile. Two separate short arms with simple mitten-like hands beside the side points, and two short rounded feet below the lower points. White unfilled body, no glow, decorations or accessories. Preserve five body points, two arms and two feet.',character:'Warm, encouraging; points out paths and helps the child notice useful details. A fantasy sky companion whose movement follows the established world rules.',artwork:'/assets/companions/lumi-star.webp'},
  {id:'mira-alien',name:'Míra',kind:'přátelský mimozemšťánek',description:'Zná hvězdné stanice a rád objevuje nové nápady.',appearance:'Small friendly alien with a pear-shaped rounded body, two short antennae each ending in one rounded bulb, large kind eyes, two simple hands, two broad feet and one plain sleeveless vest; no other clothes or accessories.',character:'Friendly, curious; guides the child through habitable space stations and helps solve simple problems. Breathing and protection must follow the world rules.',artwork:'/assets/companions/mira-alien.webp'},
  {id:'rony-rover',name:'Rony',kind:'malé měsíční vozítko',description:'Prozkoumá měsíční cestičku a pomůže odvézt nalezený poklad.',appearance:'Friendly small moon rover: one rounded rectangular body, exactly four broad smooth wheels with two on each side, two large friendly eyes on the front panel, and one short centered roof antenna ending in a round tip. No other attachments, tools, gears, clothes or accessories. Preserve wheel count, axle positions, body proportions and antenna placement from every viewpoint. A far wheel may be naturally occluded by the body or nearer wheels; never change the underlying four-wheel construction.',character:'Steady, practical; explores paths and carries small objects while the child leads. No flying or new vehicle parts without an established rule.',artwork:'/assets/companions/rony-rover.webp'},
  {id:'tonda-triceratops',name:'Tonda',kind:'laskavý triceratops',description:'Nikam nespěchá a pro kamarády má vždycky místo.',appearance:'Small friendly triceratops with four short broad legs, one short tail, a broad head frill with smooth rounded scallops and exactly three rounded horns: two above the eyes and one smaller horn on the nose. Kind eyes and a smiling closed mouth; no sharp teeth, frill spines, clothes or accessories.',character:'Gentle, dependable; helps the child move simple obstacles safely and waits for friends.',artwork:'/assets/companions/tonda-triceratops.webp'},
  {id:'riki-tyrannosaur',name:'Riki',kind:'hravý tyranosaurus',description:'Je malý průzkumník s velkou chutí pomáhat.',appearance:'Small friendly tyrannosaurus with a big rounded head, exactly two short front arms, two strong hind legs, one broad balancing tail and large kind eyes. Smiling closed mouth without visible teeth; no spikes, clothes or accessories.',character:'Playful, considerate; follows tracks and helps carry light objects without frightening anyone.',artwork:'/assets/companions/riki-tyrannosaur.webp'},
  {id:'fila-pterosaur',name:'Fíla',kind:'létající pterosaurus',description:'Z výšky zahlédne cestu, kterou ostatní snadno přehlédnou.',appearance:'Small friendly pterosaur with a long rounded beak, one simple backward head crest, exactly two broad rounded membrane wings and two small feet. Kind eyes, closed smiling mouth; no feathers, teeth, clothes or accessories.',character:'Observant, gentle; surveys routes from the air and helps the child navigate. Flies only where the established world permits flight.',artwork:'/assets/companions/fila-pterosaur.webp'}
].map((c,index)=>Object.freeze({...c,version:CATALOG_VERSION,index,reference:c.artwork||'/assets/companions-v1.png',referenceCell:c.artwork?{column:0,row:0,columns:1,rows:1}:{column:index%3,row:Math.floor(index/3),columns:3,rows:2}})));
export const getCompanion = id => COMPANION_CATALOG.find(c=>c.id===id);
// Configurator recommendations only; these are not provider restrictions.
const WORLD_COMPANIONS=Object.freeze({
 'Kouzelný les':['pip-dog','lisi-fox','borek-dragon','jiskra-unicorn','pirko-bird'],
 'Zvířecí kamarádi':['pip-dog','lisi-fox','bublik-dolphin','pirko-bird'],
 'Zatoulaný obláček':['borek-dragon','pirko-bird','lumi-star','fila-pterosaur'],
 'Podmořský svět':['bublik-dolphin','kori-turtle','oli-octopus','vlnka-seahorse'],
 'Vesmír':['blik-robot','lumi-star','mira-alien','rony-rover'],
 'Dinosauři':['dino-dinosaur','tonda-triceratops','riki-tyrannosaur','fila-pterosaur']
});
export const recommendedCompanionIds=theme=>!theme?[]:[...(WORLD_COMPANIONS[theme]||COMPANION_CATALOG.map(c=>c.id))];
export function companionContext(input){
 if(input.companion_mode==='none')return {mode:'none',instruction:'Do not add a recurring companion. The child leads the story.'};
 if(input.companion_mode==='catalog'){const c=getCompanion(input.companion_id);if(!c)throw Error('INVALID_COMPANION');return {mode:'catalog',...c,name:input.companion_name||c.name,instruction:'Keep the same appearance, clothes and character in all relevant scenes. Give this companion a real action matching the illustration. Use only its selected reference cell, never the entire cast.'};}
 return {mode:'custom',description:input.custom_companion||input.companion_type,name:input.companion_name,instruction:'Do not silently replace the requested companion. Ask for clarification if the identity is ambiguous.'};
}
