import './build-prompts.mjs';
import fs from 'node:fs';import path from 'node:path';
import {SITE,CONTACT,faqs,themes,pages} from '../content/site.mjs';
import {COMPANION_CATALOG} from '../server/companions.mjs';
import {PRODUCT, escapeHtml as e} from '../server/product.mjs';
const root=path.resolve(import.meta.dirname,'..'),dist=path.join(root,'dist');
for(const name of ['pro-skolky','ukazky','partaci']){const target=path.resolve(dist,name);if(!target.startsWith(path.resolve(dist)+path.sep))throw Error('UNSAFE_OUTPUT');fs.rmSync(target,{recursive:true,force:true});}
const story=JSON.parse(fs.readFileSync(path.join(root,'spec/sample-story.json'),'utf8'));
const write=(url,html)=>{const filename=path.join(dist,url,'index.html');fs.mkdirSync(path.dirname(filename),{recursive:true});fs.writeFileSync(filename,html);};
const button=(text='Vytvořit příběh')=>`<a class="button" href="/vytvorit/">${text}</a>`;
const gallery=()=>`<section class="story-reader" data-reader aria-label="Celý ukázkový příběh"><div class="reader-pages">${story.pages.map((p,i)=>`<figure data-page="${i}" ${i?'hidden':''}><img src="/assets/story/page-${i+1}.webp" alt="Strana ${i+1} příběhu Eliška a kouzelný les" width="1200" height="849" ${i?'loading="lazy"':''}></figure>`).join('')}</div><div class="reader-controls"><button type="button" data-previous aria-label="Předchozí strana" disabled>‹</button><div class="page-dots" aria-label="Vybrat stranu">${story.pages.map((p,i)=>`<button type="button" data-page-select="${i}" aria-label="Strana ${i+1}" aria-pressed="${!i}">${i+1}</button>`).join('')}</div><button type="button" data-next aria-label="Další strana">›</button></div><p data-reader-status role="status" aria-live="polite" class="reader-status">Strana 1 z 6</p><noscript><style>[data-reader] [data-page][hidden]{display:block!important}.reader-controls{display:none}</style></noscript></section>`;
const art=c=>c.artwork?`<img class="companion-art companion-art-single" src="${e(c.artwork)}" alt="${e(c.kind)}" width="256" height="256" loading="lazy">`:`<span class="companion-art" role="img" aria-label="${e(c.kind)}" style="--col:${c.index%3};--row:${Math.floor(c.index/3)}"></span>`;
const catalog=()=>`<div class="public-companions">${COMPANION_CATALOG.map(c=>`<article>${art(c)}<h3>${c.name}</h3><p>${c.kind}</p><small>${c.description}</small></article>`).join('')}</div>`;
const head=(title,description,url,index=true)=>`<!doctype html><html lang="cs"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | Pohádkové omalovánky</title><meta name="description" content="${e(description)}"><meta name="theme-color" content="#fffaf1"><link rel="canonical" href="${SITE+url}">${index?'':'<meta name="robots" content="noindex,follow">'}<meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${SITE+url}"><meta property="og:locale" content="cs_CZ"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Nunito:wght@600;700;800;900&display=swap" rel="stylesheet"><link rel="stylesheet" href="/editorial.css"><link rel="stylesheet" href="/design.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:title,url:SITE+url,inLanguage:'cs',description,...(url!=='/'?{breadcrumb:{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Pohádkové omalovánky',item:SITE+'/'},{'@type':'ListItem',position:2,name:title,item:SITE+url}]}}:{})}).replace(/</g,'\\u003c')}</script></head><body><a class="skip" href="#main">Přejít na obsah</a>`;
const header=()=>`<header class="header wrap"><a class="brand" href="/" aria-label="Pohádkové omalovánky – úvodní stránka"><span class="brand-fairy">Pohádkové</span><span class="brand-coloring">omalovánky</span></a></header>`;
const footer=()=>`<footer class="site-footer"><div class="wrap footer-grid"><div><a class="brand" href="/" aria-label="Pohádkové omalovánky – úvodní stránka"><span class="brand-fairy">Pohádkové</span><span class="brand-coloring">omalovánky</span></a><p>Malý příběh. Velké společné chvíle.</p></div><nav aria-label="Další informace"><a href="/pohadka-na-miru/">Pohádka na míru</a><a href="/omalovanky-z-fotky/">S fotkou i bez ní</a><a href="/navody/jak-vytisknout-omalovanky/">Jak tisknout</a><a href="/soukromi/">Soukromí</a><a href="/kontakt/">Kontakt</a></nav><button type="button" id="motion-toggle" class="motion-toggle" aria-pressed="false">Pozastavit pohyb</button></div></footer><script src="/site.js" defer></script>`;
const sampleLink=()=>`<a class="button outline" href="/assets/ukazka-pohadky.pdf" download>Stáhnout vzorový příběh v PDF</a>`;
const shell=(title,description,url,body,index=true)=>head(title,description,url,index)+header()+`<main id="main">${body}</main>`+footer()+'</body></html>';

const creationSteps=[
 {title:'Vyberte dobrodružství',short:'Hrdina, svět a parťák.',description:'Vyplňte jméno a věk dítěte, vyberte svět a parťáka. Přidejte zájmy nebo přání k příběhu. Fotografie je volitelná.',action:'Vyplnit zadání',href:'/vytvorit/',note:'Dítě je hlavním hrdinou. Parťáka mít nemusí.'},
 {title:'Zkontrolujte zadání',short:'Ať je pohádka podle vás.',description:'Prohlédněte si shrnutí a klikněte na „Zkontrolovat zadání“. Ještě před vytvořením příběhu můžete upravit jméno, prostředí i svá přání.',action:'Připravit zadání',href:'/vytvorit/',note:'Vše vyřídíte přímo tady na webu.'},
 {title:'Nechte AI tvořit',short:'Příběh, obrázky a PDF.',description:'Podle vašeho zadání AI vytvoří českou pohádku se šesti navazujícími omalovánkami. Vaše dítě se stane hlavním hrdinou a vybraný parťák ho bude provázet dobrodružstvím.',action:'Vytvořit vlastní příběh',href:'/vytvorit/',note:'Délka vyprávění i obtížnost obrázků se přizpůsobí věku dítěte.'},
 {title:'Vytiskněte a vybarvujte',short:'Šest stran společných chvil.',description:'Hotové PDF si stáhněte přímo z webu a vytiskněte na A4 na šířku. Pak už stačí pastelky, pohodlné místo a chuť společně číst a vybarvovat.',action:'Jak správně tisknout',href:'/navody/jak-vytisknout-omalovanky/',note:'Černobílý tisk stačí. Barevný zachová i barevné nápovědy v textu.'}
];
const creationJourney=()=>`<section class="creation-journey wrap" id="jak-to-funguje" aria-labelledby="journey-title" data-journey><img class="margin-scene margin-scene-space" src="/assets/scenes/boy-blik-space.webp" width="640" height="640" alt="" aria-hidden="true" loading="lazy"><div class="journey-heading"><h2 id="journey-title">Od prvního nápadu<br><em>až k pastelkám.</em></h2><p>Čtyři malé kroky k vašemu velkému dobrodružství.</p></div><div class="journey-trail" data-journey-trail><svg class="journey-line" aria-hidden="true" focusable="false"><path data-trail-stroke/><path data-trail-stroke/></svg><ol class="journey-steps">${creationSteps.map((step,i)=>`<li class="journey-stop"><details class="journey-bubble"><summary><span class="journey-marker" aria-hidden="true">${i+1}</span><span class="journey-label"><strong>${e(step.title)}</strong><span class="journey-short">${e(step.short)}</span></span><span class="journey-plus" aria-hidden="true">+</span></summary><div class="journey-detail"><p>${e(step.description)}</p><a class="button" href="${step.href}">${e(step.action)}</a><p class="journey-note">${e(step.note)}</p></div></details>${i===1?'<img class="journey-art journey-pencils" src="/assets/journey/pencils.webp" width="220" height="220" alt="" loading="lazy" aria-hidden="true">':i===2?'<img class="journey-art journey-book" src="/assets/journey/book.webp" width="220" height="220" alt="" loading="lazy" aria-hidden="true">':''}</li>`).join('')}</ol></div><div class="journey-finish"><a class="text-link" href="#ukazka" data-sample-open aria-haspopup="dialog" aria-controls="preview">Prohlédnout hotový vzor</a></div></section>`;

const home=`<section class="hero-stage"><div class="hero wrap"><div class="hero-copy"><h1>Vaše dítě.<br>V hlavní <em>roli.</em></h1><p class="hero-description">Česká pohádka na míru se šesti omalovánkami. Stačí vytisknout a dobrodružství může začít.</p><div class="hero-actions">${button('Vytvořit příběh')}</div></div><figure class="hero-product" id="ukazka"><span class="product-sticker">Jejich jméno.<br>Jejich příběh.</span><button class="book-page" id="sample-open" type="button" aria-haspopup="dialog" aria-controls="preview" aria-label="Prolistovat celý ukázkový příběh"><img class="page-preview" src="/assets/story/page-1.webp" width="1200" height="849" alt="Skutečná první strana příběhu Eliška a kouzelný les" fetchpriority="high"></button><span class="hero-mascot" aria-hidden="true">${art(COMPANION_CATALOG[1])}</span><noscript>${sampleLink()}</noscript></figure></div></section>${creationJourney()}<section class="last-call wrap story-invitation" aria-labelledby="invitation-title"><div class="invitation-copy"><h2 id="invitation-title">Další hrdina?<br><em>Ten váš.</em></h2>${button('Začít dobrodružství')}</div><img class="invitation-art" src="/assets/invitation/boy-and-lisa.webp" width="900" height="600" alt="Chlapeček a liška Lisa společně objevují květinu v kouzelném lese. Omalovánková ilustrace." loading="lazy"></section><section class="section wrap faq" id="otazky"><img class="margin-scene margin-scene-forest" src="/assets/scenes/girl-jiskra-forest.webp" width="640" height="640" alt="" aria-hidden="true" loading="lazy"><div class="section-heading centered"><p class="eyebrow">CO BY VÁS JEŠTĚ MOHLO ZAJÍMAT .....</p><h2>Než vytáhnete pastelky.</h2></div><div id="faq-list">${faqs.map(([q,a])=>`<details><summary>${e(q)}</summary><p>${e(a)}</p></details>`).join('')}</div></section>`;
write('',head('Personalizované omalovánky s příběhem – 6 stran za 80 Kč','Vaše dítě jako hrdina české pohádky se šesti omalovánkami. Prohlédněte celý příběh a vytvořte vlastní zadání. PDF k tisku za 80 Kč.','/')+header()+`<main id="main">${home}</main>`+footer()+`<dialog id="preview" class="sample-preview" aria-labelledby="preview-title"><button class="close" type="button" data-close="preview" aria-label="Zavřít ukázku" autofocus>×</button><h2 id="preview-title">Eliška a kouzelný les</h2>${gallery()}<div class="preview-download">${sampleLink()}</div></dialog><script src="/app.js"></script><script src="/journey.js" defer></script></body></html>`);
const field=(id,label,max,placeholder='',tag='input')=>`<div class="field"><label for="${id}">${label}</label><${tag} id="${id}" name="${id}" maxlength="${max}" placeholder="${placeholder}" aria-describedby="${id}-error" ${tag==='input'?'type="text" autocomplete="off"':''}>${tag==='textarea'?'</textarea>':''}<p class="error" id="${id}-error" aria-live="polite"></p></div>`;
const choice=(group,value,title,illustration='',subtitle='')=>`<label class="pick-option"><input type="radio" name="${group}" value="${e(value)}"><span class="pick-card">${illustration||'<span class="pick-symbol" aria-hidden="true">'+(value==='none'?'○':'+')+'</span>'}<strong>${e(title)}</strong>${subtitle?`<small>${e(subtitle)}</small>`:''}<span class="pick-check" aria-hidden="true">✓</span></span></label>`;
const configurator=`<section class="wrap configurator-heading"><a href="/" class="text-link">Zpět na úvod</a><h1>Vaše pohádka začíná tady.</h1><p>Představte nám hrdinu a vyberte jeho dobrodružství.</p></section><form id="configurator" class="wrap configurator" novalidate>
<section class="config-section" id="dite" aria-labelledby="child-heading"><div class="config-section-title"><b>1</b><h2 id="child-heading">Dítě jako hlavní hrdina</h2></div><div class="config-fields">${field('child_name','Jméno dítěte',30,'Například Eliška')}<div class="field"><label for="child_age">Věk dítěte</label><select id="child_age" name="child_age" aria-describedby="child_age-error"><option value="">Vyberte věk</option>${[3,4,5,6,7,8,9].map(a=>`<option value="${a}">${a} ${a<5?'roky':'let'}</option>`).join('')}</select><p class="error" id="child_age-error" aria-live="polite"></p></div></div><div class="photo-area"><label for="photo">Přidat fotografii · nepovinné</label><input id="photo" type="file" accept="image/jpeg,image/png" aria-describedby="photo-help photo-error"><p id="photo-help">Fotografie pomůže stylizovat podobu dítěte do obrázků. JPG nebo PNG, nejvýše 10 MB.</p><div id="photo-selection" hidden><img id="photo-preview" class="photo-preview" alt="Vybraná fotografie dítěte"><button type="button" class="inline-button" id="remove-photo">Odstranit fotografii</button></div><p id="photo-error" class="error" aria-live="polite"></p></div><div id="appearance-field">${field('appearance_description','Krátký popis vzhledu bez fotografie',200,'Například hnědé vlasy po ramena a kulaté brýle.','textarea')}</div></section>
<section class="config-section" id="svet" aria-labelledby="world-heading"><div class="config-section-title"><b>2</b><h2 id="world-heading">Svět příběhu</h2></div><fieldset id="theme-group" aria-describedby="theme-error"><legend>Vyberte jedno prostředí</legend><div class="pick-grid world-picks">${choice('theme','Vlastní téma','Vlastní svět','','Místo podle vaší fantazie')}${themes.map((t,i)=>choice('theme',t,t,`<img class="theme-art" src="/assets/themes/theme-${i+1}.png" alt="" width="640" height="480" loading="lazy">`)).join('')}</div><p id="theme-error" class="error" aria-live="polite"></p></fieldset><div id="custom-world-field" hidden>${field('custom_theme','Kde se má příběh odehrávat?',120,'Například zahrada, kde rostou obří jahody.','textarea')}</div></section>
<section class="config-section" id="partak" aria-labelledby="companion-heading" hidden><div class="config-section-title"><b>3</b><h2 id="companion-heading">Parťák do příběhu</h2></div><fieldset id="companion-group" aria-describedby="companion_mode-error"><legend>Vyberte jednoho parťáka, nebo příběh bez něj</legend><div class="pick-grid companion-picks">${choice('companion','custom','Vlastní parťák','','Postava, člověk nebo zvíře')}${COMPANION_CATALOG.map(c=>choice('companion','catalog:'+c.id,c.name,art(c),c.kind)).join('')}${choice('companion','none','Bez parťáka','','Výprava hlavního hrdiny')}</div><p id="companion_mode-error" class="error" aria-live="polite"></p></fieldset><div id="custom-companion-field" hidden>${field('custom_companion','Kdo bude vaším parťákem?',120,'Vlastní či známá postava, sourozenec nebo mazlíček.','textarea')}</div></section>
<section class="config-section" id="prani" aria-labelledby="wish-heading"><div class="config-section-title"><b>4</b><h2 id="wish-heading">Další přání</h2></div>${field('personal_wish','Zájmy dítěte nebo přání k příběhu · nepovinné',300,'Například miluje vláčky a rád pomáhá zvířátkům.','textarea')}<p class="field-hint">Nejvýše 300 znaků.</p><details class="optional-details"><summary>Chci popsat konkrétní scénu</summary>${field('requested_scenes','Co se má v příběhu stát? · nepovinné',500,'','textarea')}</details></section>
<section class="config-section config-summary" id="shrnuti" aria-labelledby="summary-heading"><div class="config-section-title"><b>5</b><h2 id="summary-heading">Vaše zadání</h2></div><dl id="live-summary" aria-live="polite"></dl><p>Nový AI příběh se <strong>${PRODUCT.pages} stranami a ${PRODUCT.pages} omalovánkami</strong> v jednom PDF.</p><div class="config-submit"><p>Výsledné PDF <strong>${PRODUCT.priceCzk} Kč</strong><small>Sestavení a kopírování promptu je bez platby.</small></p><button class="button" id="check-submit" type="submit">Zkontrolovat zadání</button></div><p class="field-hint">Fotografii ani údaje dítěte nevkládáme do URL nebo analytiky.</p></section></form>
<dialog id="check-dialog" class="check-dialog" aria-labelledby="check-title"><button class="close" type="button" id="close-check" aria-label="Zavřít kontrolu">×</button><h2 id="check-title">Kontrola zadání</h2><div id="check-result" role="status" aria-live="polite"></div><dl id="check-summary" class="dialog-summary"></dl><p class="photo-copy-note" id="photo-copy-note" hidden>Fotografii dítěte přiložte v ChatGPT zvlášť.</p><div class="check-actions"><button type="button" class="button" id="copy-prompt">Zkopírovat prompt pro ChatGPT</button><button type="button" class="button outline" id="retry-check" hidden>Opakovat kontrolu</button><button type="button" class="button outline" id="edit-input">Upravit zadání</button><button type="button" class="button outline" id="continue-payment" hidden>Pokračovat k platbě</button></div><p id="copy-status" role="status" aria-live="polite"></p><details id="prompt-details"><summary>Zobrazit celý výsledný prompt</summary><label for="prompt-preview" class="field-label">Aktuální prompt</label><textarea id="prompt-preview" readonly spellcheck="false"></textarea><button type="button" class="button outline" id="select-prompt">Označit text pro ruční kopírování</button></details><p class="field-hint">Sestavení a kopírování promptu nespouští placené AI generování. Předběžná kontrola není zárukou přijetí všech obrázků.</p></dialog>`;
write('/vytvorit/',shell('Vytvořit vlastní příběh','Sestavte zadání příběhu se šesti omalovánkami a zkopírujte úplný prompt pro ChatGPT.','/vytvorit/',configurator,false).replace('</body>','<script type="module" src="/configurator.mjs"></script></body>'));
const runtime=path.join(dist,'runtime');fs.mkdirSync(runtime,{recursive:true});
for(const name of ['product','companions','prompts','story-schema'])fs.copyFileSync(path.join(root,'server',name+'.mjs'),path.join(runtime,name+'.mjs'));
fs.writeFileSync(path.join(runtime,'story-brief.mjs'),fs.readFileSync(path.join(root,'shared/story-brief.mjs'),'utf8').replaceAll('../server/','./'));
for(const p of pages)write(p.path,shell(p.title,p.description,p.path,`<section class="wrap article-hero"><p class="eyebrow">MOJE POHÁDKA</p><h1>${p.heading}</h1><p>${p.lead}</p>${button('Připravit vlastní příběh',p.theme)}</section><div class="wrap article-layout"><article>${p.sections.map(([h,t])=>`<section><h2>${h}</h2><p>${t}</p></section>`).join('')}<p><a href="/#ukazka">Prohlédnout celý vzor</a> · <a href="/navody/jak-vytisknout-omalovanky/">Návod na tisk</a></p></article>${p.sample?`<aside><img src="/assets/story/page-1.webp" width="1200" height="849" alt="První strana ukázky pro čtyřleté dítě" loading="lazy">${sampleLink()}</aside>`:''}</div>`));
write('/kontakt/',shell('Kontakt','Kontakt pro vaše dotazy.','/kontakt/',`<section class="wrap article-hero"><h1>Ozvěte se nám.</h1><p><a href="mailto:${CONTACT}">${CONTACT}</a></p><p>Kontaktní adresa pro vaše dotazy. Údaje o provozovateli a obchodní podmínky budou doplněny před zahájením prodeje.</p></section>`));
write('/soukromi/',shell('Soukromí v ukázkovém provozu','Jak současný náhled zachází se zadáním a volitelnou fotografií dítěte.','/soukromi/',`<section class="wrap article-hero"><h1>Vaše zadání zůstává soukromé.</h1><p>V aktuálním náhledu se údaje drží v paměti formuláře. Po obnovení stránky se vymažou.</p></section><article class="wrap prose"><h2>Fotografie a kontrola</h2><p>Fotografie je volitelná. Kliknutím na kontrolu odešlete zadání a případný soubor serveru. Současná nepřipojená kontrola data neukládá ani nepředává generativní AI. Zákaznické příběhy a fotografie nejsou veřejné SEO stránky.</p><h2>Měření a externí zdroje</h2><p>V této revizi není aktivní odesílání návštěvnické analytiky. Písma se načítají přes Google Fonts. Nastavení pohybu se pamatuje jen po dobu otevřené stránky.</p><h2>Před zahájením prodeje</h2><p>Musí být doplněn správce údajů, zpracovatelé, konkrétní retenční pravidla a úplné informační povinnosti. Tato stránka popisuje současný náhled.</p><p>Dotazy: <a href="mailto:${CONTACT}">${CONTACT}</a></p></article>`));
fs.writeFileSync(path.join(dist,'404.html'),shell('Stránka nebyla nalezena','Zkuste úvodní stránku nebo ukázkový příběh.','/404/',`<section class="wrap article-hero"><h1>Tudy příběh nevede.</h1><p>Stránka neexistuje nebo už změnila adresu.</p><a class="button" href="/">Zpět na začátek</a></section>`,false));
const urls=['/',...pages.map(p=>p.path),'/kontakt/','/soukromi/'];
fs.writeFileSync(path.join(dist,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(url=>`<url><loc>${SITE+url}</loc></url>`).join('')+'</urlset>');
fs.writeFileSync(path.join(dist,'robots.txt'),`User-agent: *\nAllow: /\nDisallow: /api/\nDisallow: /objednavka/\nDisallow: /soukrome/\nSitemap: ${SITE}/sitemap.xml\n`);
console.log(`Generated ${urls.length} useful HTML pages and sitemap; no thin keyword pages.`);
